# Generated by Django 5.2.9 on 2026-02-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('frequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ligne')),
            ],
        ),
    ]
