# Generated by Django 5.2.9 on 2026-03-10 01:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20260223_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('idbus', models.AutoField(db_column='idbus', primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=30, null=True)),
                ('kilometrage', models.FloatField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'bus',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='arret',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ligne',
            options={'managed': False},
        ),
    ]
