# Generated by Django 5.2.11 on 2026-04-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bus_alter_arret_options_alter_ligne_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arret',
            table='arret',
        ),
        migrations.AlterModelTable(
            name='ligne',
            table='ligne',
        ),
    ]
