# Generated by Django 5.2.11 on 2026-04-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_arret_table_alter_ligne_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arret',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ligne',
            options={},
        ),
    ]
