# Generated by Django 5.2.11 on 2026-04-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_arret_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arret',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ligne',
            options={'managed': False},
        ),
    ]
